Traceback (most recent call last):
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a.var(), np.trapz(np.abs(S_aa), freq)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_26956/3117648536.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0ma[0m[1;33m.[0m[0mvar[0m[1;33m([0m[1;33m)[0m[1;33m,[0m [0mnp[0m[1;33m.[0m[0mtrapz[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0mabs[0m[1;33m([0m[0mS_aa[0m[1;33m)[0m[1;33m,[0m [0mfreq[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mNameError[0m: name 'S_aa' is not defined
NameError: name 'S_aa' is not defined

